### ISSUE TITLE
test whit and without mr different value in f1

### ISSUE THREAD

**Issue by astro80** [RealismusModding/FS17_RM_soilCompaction#29] opened 2018-06-12 21:31 UTC
i try with horsh pronto 9c and with mr in the f1 menu says no compcation effect but on the field i have light compaction. without mr f1 menu says light compaction and in the field i had light compaction.

**Comment by reallogger** [comment] 2018-06-12 21:54
Just tested and confirmed the Pronto 9C gives no compaction with MR, which is quite ok in itself. I used a Fendt 930 with standard wheels to pull the seeder. The tractor gave light compaction. If you look closely you should see that the cause of the compaction is the tractor, not the seeder as the whole field is not compacted. Now if you used a tractor with wider wheels the tractor will compact the ground before the seeder passes.

The second test I did was to use the Challenger MT700E pulling the seeder. With MR, the MT700E gives no compaction. In this test the field was planted without any compaction as neither the tractor or seeder gave any soil compaction.

**Comment by reallogger** [comment] 2018-08-09 17:11
No further info here so closing this

**Closed as completed by reallogger** 2018-08-09 17:11 UTC
